# Generated by Django 3.0.3 on 2020-03-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200329_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
