# Generated by Django 3.0.3 on 2020-03-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professor_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='user_id',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='first_name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='last_name',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='password',
            new_name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='photo',
        ),
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='professors'),
        ),
    ]
