# Generated by Django 3.0.3 on 2020-03-08 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200308_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='nome',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='senha',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='sobrenome',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='foto',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='id_usuario',
            new_name='user_id',
        ),
    ]
