# Generated by Django 3.0.3 on 2020-03-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200308_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
